### ISSUE TITLE
Crash when try to decode invalid images

### ISSUE THREAD

**Issue by hanleirx** [chuganzy/HCImage-BPG#23] opened 2016-10-18 08:53 UTC
Hello，I use your project,but I met a problem--

``` objc++
if (bpg_decoder_decode(this->_context, buffer, length) != 0) {
    bpg_decoder_close(this->_context);
    throw "bpg_decoder_decode";
}
```

here,my demo will crash, I don't know why. Maybe I can't use your project,can I look how you use it?Thank you!

**Comment by chuganzy** [comment] 2016-10-18 15:50
@hanleirx Hi! Thanks for you report. I'll check it, so please let me know more details about it.
1. Which platform and device are you using? iOS or macOS?
2. If you do, please provide me some sample BGP format images which cause this crash. This exception is thrown when the BPG image is invalid (but not crash).
3. How did you install this library to your project? CocoaPods, Carthage or others?

**Comment by hanleirx** [comment] 2016-10-19 01:21
OK
1 iOS
2 My picture is ".jpg",and I use it like this 
```objc
NSString *filePath = [[NSBundle mainBundle] pathForResource:@"aaaaa" ofType:@"jpg"];
NSData *data = [NSData dataWithContentsOfFile:filePath];
UIImage *imagea = [UIImage imageWithBPGData:data];
```
3 CocoaPods

**Comment by chuganzy** [comment] 2016-10-24 16:33
Thanks for your reply. Which version of Xcode did you use for? @hanleirx

**Comment by hanleirx** [comment] 2016-10-27 02:59
Xcode8

**Comment by chuganzy** [comment] 2016-12-24 09:21
@hanleirx Sorry for having kept you wait, but I could not reproduce this issue under the same situation.

Didn't you add an [Exception Breakpoint](http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions)? If so, it's all fine - doesn't kill the app and behaves correctly (i.e. returned image should be nil). When we try to decode an invalid data, the decoder throws an exception which is handled [here](https://github.com/chuganzy/HCImage-BPG/blob/master/HCImage%2BBPG/HCImage%2BBPG.mm#L175-L180).

I think this is not a library-side issue. Decoding invalid format data is already [well-tested](https://github.com/chuganzy/HCImage-BPG/blob/master/Tests/Tests.swift#L35-L39) and no way to cause this issue directly so gonna close it.

Anyway, thanks for your report☺️

**Closed as completed by chuganzy** 2016-12-24 09:21 UTC
